server:
  port: 4004

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.burstCapacity: 5
            redis-rate-limiter.replenishRate: 5
#            What the above param do is - in a second 5 request can be done by same ip and then if it exceeds it will not get any response until the next 1 second . After that reset will happen and again user can do next 5 request in a single sencond
            key-resolver: "#{@ipKeyResolver}"
      routes:
#          input address now - http://localhost:4004/auth/login
#          After filter Api becomes - http://auth-service:4005/login
          - id: auth-service-route
            uri: http://auth-service:4005
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1

#          "Patient-service microservice's" API mapping
#          REST CLIENT -> http://localhost:4004/api/patients      <Input request to api gateway>
#          API GATEWAY -> http://patient-service:4000/patients    <Output request from api gateway according to rules >
#          PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array  <Microservice will read this api when request lands from api gateway to microservice>
          - id: patient-service-route
            uri: http://patient-service:4000
            predicates:
              - Path=/api/patients/**
            filters:
              - StripPrefix=1
              - JwtValidation

#          "Appointment-service microservice's" API mapping
#          REST CLIENT -> http://localhost:4004/api/appointments      <Input request to api gateway>
#          API GATEWAY -> http://appointment-service:4006/appointments    <Output request from api gateway according to rules >
#          PATIENT SERVICE (SPRING BOOT APP) -> /appointments -> Appointments Array  <Microservice will read this api when request lands from api gateway to microservice>
          - id: appointment-service-route
            uri: http://appointment-service:4006
            predicates:
              - Path=/api/appointments/**
            filters:
              - StripPrefix=1
              - JwtValidation


  #         "API documentation's" API mapping '
  #         REST CLIENT -> http://localhost:4004/api-docs/patients
  #         API GATEWAY -> http://patient-service:4000/v3/api-docs
          - id: api-docs-patient-route
            uri: http://patient-service:4000
            predicates:
              - Path=/api-docs/patients
            filters:
              - RewritePath=/api-docs/patients,/v3/api-docs

  #         "API documentation's" API mapping '
  #         REST CLIENT -> http://localhost:4004/api-docs/auth
  #         API GATEWAY -> http://auth-service:4005/v3/api-docs

          - id: api-docs-auth-route
            uri: http://auth-service:4005
            predicates:
              - Path=/api-docs/auth
            filters:
              - RewritePath=/api-docs/auth,/v3/api-docs

#         "API documentation's" API mapping '
#         REST CLIENT -> http://localhost:4004/api-docs/auth
#         API GATEWAY -> http://auth-service:4006/v3/api-docs

          - id: api-docs-appointment-route
            uri: http://appointment-service:4006
            predicates:
              - Path=/api-docs/appointments
            filters:
              - RewritePath=/api-docs/appointments,/v3/api-docs