server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
#          "Patient-service microservice's" API mapping
#          REST CLIENT -> http://localhost:4004/api/patients      <Input request to api gateway>
#          API GATEWAY -> http://patient-service:4000/patients    <Output request from api gateway according to rules >
#          PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array  <Microservice will read this api when request lands from api gateway to microservice>
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1


#         "API documentation's" API mapping '
#         REST CLIENT -> http://localhost:4004/api-docs/patients
#         API GATEWAY -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs