### Post request for creating new patient record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Blessing Obedayu",
  "email": "blessing17@dfg.com",
  "address": "111 Yohail Mosef street Near Town hall, Tel Aviv - Israel",
  "dateOfBirth": "1978-09-09",
  "registeredDate": "2025-12-02"
}

###