spring.application.name=patient-service

#UNCOMMENT TO USE IN-MEMORY DATABASE WHENEVER NOT USING DOCKER IMAGES
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
##For Synching with entities
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

server.port=4000

logging.level.root=info

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#For Kafka producer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
#Total time a message transmission can take.
spring.kafka.producer.properties.delivery.timeout.ms=180000
#Time the client waits for a response from the broker.
spring.kafka.producer.properties.request.timeout.ms=60000
#Time the producer blocks waiting for buffer space/metadata.
spring.kafka.producer.properties.max.block.ms=120000

#Below line is for telling circuitbreaker that evaluate last 10 requests before tipping the circuit to alternate route.
resilience4j.circuitbreaker.instances.billingService.slidingWindowSize=10
#Below line is for telling circuitbreaker that there must be minimum 5 number of calls before calculating failure rate for circuit breaker.
resilience4j.circuitbreaker.instances.billingService.minimumNumberOfCalls=5
#Below line is for telling circuitbreaker that this means circuitbreaker will tipp the circuit when failure rate of total requests is exceeding 50% rate
resilience4j.circuitbreaker.instances.billingService.failureRateThreshold=50
#Below line is for telling circuitbreaker that This will make 'order' to the circuitbreaker to be tipped to alternate route till the next 10 seconds and then
# starts the process of evaluating whether to tipp-off or not
resilience4j.circuitbreaker.instances.billingService.waitDurationInOpenState=10s
#This tells that after 10 seconds of tipping and then coming to evaluation state (open state),
# Circuitbreaker will permit 3 test request evaluation to decide whether to continue tipped or come to normal state.
resilience4j.circuitbreaker.instances.billingService.permittedNumberOfCallsInHalfOpenState=3
#It automatically goes from open state(Alternate state) to half openstate(Evaluating state) with help of new request because request ,
# retries and recovery testing all done on new request .
# Here we are suggesting to not be depended on new request and take the decision whenver circuitbreaker feels that it is right to close the circuit once again.
resilience4j.circuitbreaker.instances.billingService.automaticTransitionFromOpenToHalfOpenEnabled=true
#Before starting the circuit breaker testing we want resilience to have atmost 2 retry attempts for sending the billing service request
resilience4j.retry.instances.billingretry.maxAttempts=2
#This means after resilience retry of max 2 attempts (as decided above) we will wait for 500 ms more and then if that too fails then circuit breaker will
# start its process. These two retry logics are managing the scenario of casual network blip which should not be treated as failure due to billing microservice failure.
resilience4j.retry.instances.billingretry.waitDuration=500ms


