# KRaft mode
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@kafka:9093

# Listeners
listeners=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
advertised.listeners=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

controller.listener.names=CONTROLLER

# Logging
log.dirs=/kafka-logs
auto.create.topics.enable=true


#services:
#  kafka:
#    image: apache/kafka:3.9.0
#    container_name: kafka-broker
#    user: "0:0"
#    networks:
#      - internal
#
#    environment:
#      KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
#
#    volumes:
#      - ./server.properties:/opt/kafka/config/kraft/server.properties
#      - kafka_data:/kafka-logs
#
#    ports:
#      - "9092:9092"
#      - "9094:9094"
#
#    restart: always
#
#volumes:
#  kafka_data:
#
#networks:
#  internal:
#    external: true
#